name: XRayPotions
version: 1.0
description: Brew and use X-Ray potions!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.20

main: com.kaelkirk.XRayPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}