name: SuperBundles
version: 1.0
description: No more inventory clutter!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.21

main: com.kaelkirk.SpigotPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}