name: Everblade
version: 1.0
description: Level up your sword!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.20

main: com.kaelkirk.SpigotPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}