name: Telekinesis
version: 1.0
description: Modify blocks with your mind!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.21
depend: [WorldGuard]

main: com.kaelkirk.SpigotPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}