name: MegaOak
version: 1.0
description: Generate mega oak trees!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.20

main: com.kaelkirk.MegaOakPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}