name: MobicalGrow
version: 1.0
description: Farm animals like never before!
author: Kaelinator&JavaBean
website: twitch.tv/kaelinator17
api-version: 1.20

main: com.kaelkirk.SpigotPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}