name: LimitlessVoid
version: 1.0
description: A new forgotten dimension...
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.20

main: com.kaelkirk.LimitlessVoidPlugin

commands:
  world:
    description: Teleport to or unload a world
    permission: op
    usage:
          /world [list|tp|unload] [world-name|player-name] [world-name]

permissions: {}