name: Backflip
version: 1.0
description: Do a backflip!
author: Kaelinator
website: twitch.tv/kaelinator17
api-version: 1.21

main: com.kaelkirk.BackflipPlugin

# commands:
#     example:
#         description: An example command
#         permission: spigotplugin.example
#         usage: /<command>

permissions: {}